// Generated by https://quicktype.io

import { Category } from "./category";
import { Marker } from "./marker";

export type privacyOptions = "public" | "unlisted" | "private";
export type usersCanCreateMarkersOptions = "yes" | "no" | "only_logged_in";

export interface Map {
    slug: string;
    title: string;
    description: string;
    privacy: privacyOptions;
    users_can_create_markers: usersCanCreateMarkersOptions;
    options: Options;
    uuid: string;
    created_at: Date;
    updated_at: Date;
    token?: string;
    categories?: Category[];
    markers?: Marker[];
}

export interface Options {
    links: "required" | "optional" | "disabled";
    default_expiration_time: number | null;
    limit_to_geographical_body_type: "land" | "water" | "no";
}
