// Generated by https://quicktype.io

import { Category } from "./category";

export interface Marker {
    id: number;
    location: Location;
    category_id: number;
    created_at: Date;
    updated_at: Date;
    description: string;
    expires_at: null;
    is_spam: boolean;
    link: string | null;
    elevation: number | null;
    category: Category;
    token?: string;
}

export interface Location {
    type: string;
    coordinates: number[];
}

export interface MarkerForm {
    lat: string;
    lng: string;
    elevation: string | number | null,
    category_name: string;
    description: string;
    link: string | null;
}