// Generated by https://quicktype.io

import { Category } from "./category";

export interface Marker {
    id: number;
    location: Location;
    category_id: number;
    created_at: Date;
    updated_at: Date | string;
    description: string | null;
    expires_at: Date | null;
    is_spam: boolean;
    link: string | null;
    elevation: number | null;
    category: Category;
    token?: string;
    address?: string | null;
    locations_count?: number;
    zoom?: number;
    heading?: number;
    pitch?: number;
    roll?: number;
    speed?: number;
    inbound_course?: number;
    groundspeed?: number;
    meta?: JSON;
}

export interface Location {
    type: string;
    coordinates: [number, number];
}

export interface MarkerForm {
    lat: string;
    lng: string;
    elevation: string | number | null,
    category_name: string;
    description: string;
    link: string | null;
    zoom?: string | number;
}