// Generated by https://quicktype.io

export interface Marker {
    id: number;
    location: Location;
    category_id: number;
    created_at: Date;
    updated_at: Date;
    description: string;
    expires_at: null;
    is_spam: boolean;
    link: null;
    category: Category;
}

export interface Category {
    id: number;
    name: string;
    slug: string;
    icon: string;
}

export interface Location {
    type: string;
    coordinates: number[];
}